// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jsNYip8tpPJLBlaUfJg5gGfwtnpc4Ho',
    appId: '1:34313396173:web:e482f7f8c9e69945b9ae84',
    messagingSenderId: '34313396173',
    projectId: 'testy-dbfbf',
    authDomain: 'testy-dbfbf.firebaseapp.com',
    storageBucket: 'testy-dbfbf.firebasestorage.app',
    measurementId: 'G-JM35F5SVQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEp4y_DQaEQxO0LNi9w_JFJrWod5Qp9KA',
    appId: '1:370409265825:android:b2966d5d3f98b469296ee0',
    messagingSenderId: '370409265825',
    projectId: 'tasky-901de',
    storageBucket: 'tasky-901de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRmGwbnBg1WuPr8PWwpWq2bFPrl7fKi4',
    appId: '1:370409265825:ios:2a557d1ce49489cb296ee0',
    messagingSenderId: '370409265825',
    projectId: 'tasky-901de',
    storageBucket: 'tasky-901de.firebasestorage.app',
    iosBundleId: 'com.example.testy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbUlWUbA-kY0eBY6-BeNVSXaV-Ztl35BY',
    appId: '1:34313396173:ios:b6245842bc7aaa93b9ae84',
    messagingSenderId: '34313396173',
    projectId: 'testy-dbfbf',
    storageBucket: 'testy-dbfbf.firebasestorage.app',
    iosBundleId: 'com.example.testy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jsNYip8tpPJLBlaUfJg5gGfwtnpc4Ho',
    appId: '1:34313396173:web:32956333b32cb715b9ae84',
    messagingSenderId: '34313396173',
    projectId: 'testy-dbfbf',
    authDomain: 'testy-dbfbf.firebaseapp.com',
    storageBucket: 'testy-dbfbf.firebasestorage.app',
    measurementId: 'G-TXLVBBPTZL',
  );
}